name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the main image (default Dockerfile)
      - name: Build main Docker image
        run: |
          docker build -t aleixmt/desmume-cli:latest .

      # Step 4: Build the watchdog image (custom Dockerfile)
      - name: Build watchdog Docker image
        run: |
          docker build -t aleixmt/desmume
          -watchdog:latest -f watchdog.Dockerfile .

      # Step 5: Push the main image
      - name: Push main Docker image
        run: |
          docker push aleixmt/desmume-cli:latest

      # Step 6: Push the watchdog image
      - name: Push watchdog Docker image
        run: |
          docker push aleixmt/desmume-watchdog:latest